### ISSUE TITLE
[3.0.2-pre] Thumbnail request fails with ampersand in filename

### ISSUE THREAD

**Issue by de-es** [haiwen/seadroid#1028]
Seadroid doesn't seem to send the right request to Seahub to get the thumbnail when there is an ampersand char in the filename.

Example from nginx log:

```
"GET /api2/repos/ad4309e9-b291-498d-9970-8d18cc0528ef/thumbnail/?p=/image%20with%20&%20in%20filename.jpg&size=128 HTTP/2.0" 400
```

Downloading the file works and the Seahub web interface doesn't have that problem.

Example from nginx log for Seahub for the same file:

```
"GET /thumbnail/ad4309e9-b291-498d-9970-8d18cc0528ef/48/image%20with%20%26%20in%20filename.jpg HTTP/2.0" 200
```

Other (image) files without ampersand work fine.

**Comment by zhwanng** [comment]
it has been fixed in v3.0.4.

**Comment by de-es** [comment]
@zhwanng It is not completely fixed. The image sizes for list and grid view are working now. But if I tap on an image to zoom in, it's still broken:

```
GET /api2/repos/ad4309e9-b291-498d-9970-8d18cc0528ef/thumbnail/?p=/image%20with%20&%20in%20filename.jpg&size=788 HTTP/2.0" 400
```
