### ISSUE TITLE
Application crash on start

### ISSUE THREAD

**Issue by eduardosm** [haiwen/seadroid#759]
Steps to reproduce:

- Start the application
- The application immediately crashes

Version: Tested both 2.2.6 from Google Play and 2.2.7 from F-Droid.

From the logcat, it looks like it is trying to access the SD card (`/storage/41FE56CD5B7D9E05/Android/media`) which having permission. I think that should be not be treated as a fatal error. 

Logcat:
```
09-23 11:11:50.100   913   923 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.seafile.seadroid2/.ui.activity.BrowserActivity bnds=[312,1222][584,1592]} from uid 10023
09-23 11:11:50.147   913   923 I ActivityManager: Start proc 24246:com.seafile.seadroid2/u0a120 for activity com.seafile.seadroid2/.ui.activity.BrowserActivity
09-23 11:11:50.207 14333 14354 W libEGL  : EGLNativeWindowType 0x6fe8159010 disconnect failed
09-23 11:11:50.312   913  5078 D VoldConnector: SND -> {226 volume mkdirs /storage/41FE56CD5B7D9E05/Android/media/com.seafile.seadroid2/}
09-23 11:11:50.319   913   982 D VoldConnector: RCV <- {200 226 Command succeeded}
09-23 11:11:50.328   913  5078 D VoldConnector: SND -> {227 volume mkdirs /storage/41FE56CD5B7D9E05/Android/data/com.seafile.seadroid2/cache/}
09-23 11:11:50.337   913   982 D VoldConnector: RCV <- {200 227 Command succeeded}
09-23 11:11:50.348 24246 24246 W System.err: java.lang.IllegalArgumentException: Invalid path: /storage/41FE56CD5B7D9E05/Android/media
09-23 11:11:50.348 24246 24246 W System.err: 	at android.os.StatFs.doStat(StatFs.java:51)
09-23 11:11:50.348 24246 24246 W System.err: 	at android.os.StatFs.<init>(StatFs.java:41)
09-23 11:11:50.348 24246 24246 W System.err: 	at com.seafile.seadroid2.data.StorageManagerLollipop.getStorageFreeSpace(StorageManagerLollipop.java:38)
09-23 11:11:50.348 24246 24246 W System.err: 	at com.seafile.seadroid2.data.StorageManager.fillLocationInfo(StorageManager.java:116)
09-23 11:11:50.348 24246 24246 W System.err: 	at com.seafile.seadroid2.data.StorageManager.getStorageLocations(StorageManager.java:202)
09-23 11:11:50.348 24246 24246 W System.err: 	at com.seafile.seadroid2.data.StorageManager.lookupStorageLocation(StorageManager.java:319)
09-23 11:11:50.348 24246 24246 W System.err: 	at com.seafile.seadroid2.data.StorageManager.getStorageLocation(StorageManager.java:336)
09-23 11:11:50.348 24246 24246 W System.err: 	at com.seafile.seadroid2.data.StorageManager.getThumbnailsDir(StorageManager.java:409)
09-23 11:11:50.348 24246 24246 W System.err: 	at com.seafile.seadroid2.SeadroidApplication.initImageLoader(SeadroidApplication.java:44)
09-23 11:11:50.348 24246 24246 W System.err: 	at com.seafile.seadroid2.SeadroidApplication.onCreate(SeadroidApplication.java:26)
09-23 11:11:50.348 24246 24246 W System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
09-23 11:11:50.348 24246 24246 W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
09-23 11:11:50.348 24246 24246 W System.err: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
09-23 11:11:50.348 24246 24246 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
09-23 11:11:50.348 24246 24246 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-23 11:11:50.348 24246 24246 W System.err: 	at android.os.Looper.loop(Looper.java:164)
09-23 11:11:50.348 24246 24246 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
09-23 11:11:50.348 24246 24246 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-23 11:11:50.348 24246 24246 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
09-23 11:11:50.348 24246 24246 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
09-23 11:11:50.349 24246 24246 W System.err: Caused by: android.system.ErrnoException: statvfs failed: EACCES (Permission denied)
09-23 11:11:50.349 24246 24246 W System.err: 	at libcore.io.Linux.statvfs(Native Method)
09-23 11:11:50.349 24246 24246 W System.err: 	at libcore.io.BlockGuardOs.statvfs(BlockGuardOs.java:330)
09-23 11:11:50.349 24246 24246 W System.err: 	at android.system.Os.statvfs(Os.java:556)
09-23 11:11:50.349 24246 24246 W System.err: 	at android.os.StatFs.doStat(StatFs.java:49)
09-23 11:11:50.349 24246 24246 W System.err: 	... 19 more
09-23 11:11:50.350 24246 24246 D AndroidRuntime: Shutting down VM
09-23 11:11:50.351 24246 24246 E AndroidRuntime: FATAL EXCEPTION: main
09-23 11:11:50.351 24246 24246 E AndroidRuntime: Process: com.seafile.seadroid2, PID: 24246
09-23 11:11:50.351 24246 24246 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.seafile.seadroid2.SeadroidApplication: java.lang.IllegalArgumentException: Invalid path: /storage/41FE56CD5B7D9E05/Android/media
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Invalid path: /storage/41FE56CD5B7D9E05/Android/media
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at android.os.StatFs.doStat(StatFs.java:51)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at android.os.StatFs.<init>(StatFs.java:41)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at com.seafile.seadroid2.data.StorageManagerLollipop.getStorageSize(StorageManagerLollipop.java:31)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at com.seafile.seadroid2.data.StorageManager.fillLocationInfo(StorageManager.java:117)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at com.seafile.seadroid2.data.StorageManager.getStorageLocations(StorageManager.java:202)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at com.seafile.seadroid2.data.StorageManager.lookupStorageLocation(StorageManager.java:319)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at com.seafile.seadroid2.data.StorageManager.getStorageLocation(StorageManager.java:336)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at com.seafile.seadroid2.data.StorageManager.getThumbnailsDir(StorageManager.java:409)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at com.seafile.seadroid2.SeadroidApplication.initImageLoader(SeadroidApplication.java:44)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at com.seafile.seadroid2.SeadroidApplication.onCreate(SeadroidApplication.java:26)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	... 8 more
09-23 11:11:50.351 24246 24246 E AndroidRuntime: Caused by: android.system.ErrnoException: statvfs failed: EACCES (Permission denied)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at libcore.io.Linux.statvfs(Native Method)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at libcore.io.BlockGuardOs.statvfs(BlockGuardOs.java:330)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at android.system.Os.statvfs(Os.java:556)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	at android.os.StatFs.doStat(StatFs.java:49)
09-23 11:11:50.351 24246 24246 E AndroidRuntime: 	... 19 more
09-23 11:11:50.357   913  5078 W ActivityManager:   Force finishing activity com.seafile.seadroid2/.ui.activity.BrowserActivity
```

**Comment by freeplant** [comment]
It has been fixed in v2.2.8.

**Comment by eduardosm** [comment]
It is still crashing in 2.2.8 with a stack trace that looks identical.

```
10-13 09:36:19.351   896  8289 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.seafile.seadroid2/.ui.activity.BrowserActivity bnds=[312,266][584,636]} from uid 10023
10-13 09:36:19.410   896  8289 I ActivityManager: Start proc 513:com.seafile.seadroid2/u0a121 for activity com.seafile.seadroid2/.ui.activity.BrowserActivity
10-13 09:36:19.427   561   561 I GRALLOC :       shrFd=10,fmt=0x1,intFmt=0x1,btStrd=5888,size=15073280,pid=561 
10-13 09:36:19.427   561   561 I GRALLOC :       yuv=2,w=1440,h=2560,Stride u=0 v=0,offset u=0 v=0 
10-13 09:36:19.427   561   561 I GRALLOC :       iova_size=15073280,conUsg=0x906,proUsg=0x966,   strd=1472,[afbc]HdrStrd=0 PyldStrd=0 Scrmbl=0,ionhnd = 1 
10-13 09:36:19.473   598   971 E BufferQueueProducer: [org.lineageos.trebuchet/com.android.launcher3.searchlauncher.SearchLauncher#0] disconnect: not connected (req=1)
10-13 09:36:19.474  1789  1870 W libEGL  : EGLNativeWindowType 0x7b19ab8010 disconnect failed
10-13 09:36:19.572   896  8289 D VoldConnector: SND -> {1260 volume mkdirs /storage/41FE56CD5B7D9E05/Android/media/com.seafile.seadroid2/}
10-13 09:36:19.576   896   972 D VoldConnector: RCV <- {200 1260 Command succeeded}
10-13 09:36:19.589   896  8289 D VoldConnector: SND -> {1261 volume mkdirs /storage/41FE56CD5B7D9E05/Android/data/com.seafile.seadroid2/cache/}
10-13 09:36:19.593   896   972 D VoldConnector: RCV <- {200 1261 Command succeeded}
10-13 09:36:19.605   513   513 W System.err: java.lang.IllegalArgumentException: Invalid path: /storage/41FE56CD5B7D9E05/Android/media
10-13 09:36:19.605   513   513 W System.err:    at android.os.StatFs.doStat(StatFs.java:51)
10-13 09:36:19.605   513   513 W System.err:    at android.os.StatFs.<init>(StatFs.java:41)
10-13 09:36:19.605   513   513 W System.err:    at com.seafile.seadroid2.data.StorageManagerLollipop.getStorageFreeSpace(StorageManagerLollipop.java:38)
10-13 09:36:19.605   513   513 W System.err:    at com.seafile.seadroid2.data.StorageManager.fillLocationInfo(StorageManager.java:116)
10-13 09:36:19.605   513   513 W System.err:    at com.seafile.seadroid2.data.StorageManager.getStorageLocations(StorageManager.java:202)
10-13 09:36:19.605   513   513 W System.err:    at com.seafile.seadroid2.data.StorageManager.lookupStorageLocation(StorageManager.java:319)
10-13 09:36:19.605   513   513 W System.err:    at com.seafile.seadroid2.data.StorageManager.getStorageLocation(StorageManager.java:336)
10-13 09:36:19.605   513   513 W System.err:    at com.seafile.seadroid2.data.StorageManager.getThumbnailsDir(StorageManager.java:409)
10-13 09:36:19.605   513   513 W System.err:    at com.seafile.seadroid2.SeadroidApplication.initImageLoader(SeadroidApplication.java:44)
10-13 09:36:19.605   513   513 W System.err:    at com.seafile.seadroid2.SeadroidApplication.onCreate(SeadroidApplication.java:26)
10-13 09:36:19.605   513   513 W System.err:    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
10-13 09:36:19.605   513   513 W System.err:    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
10-13 09:36:19.605   513   513 W System.err:    at android.app.ActivityThread.-wrap1(Unknown Source:0)
10-13 09:36:19.605   513   513 W System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
10-13 09:36:19.605   513   513 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:106)
10-13 09:36:19.605   513   513 W System.err:    at android.os.Looper.loop(Looper.java:164)
10-13 09:36:19.605   513   513 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6494)
10-13 09:36:19.605   513   513 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
10-13 09:36:19.605   513   513 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
10-13 09:36:19.605   513   513 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
10-13 09:36:19.605   513   513 W System.err: Caused by: android.system.ErrnoException: statvfs failed: EACCES (Permission denied)
10-13 09:36:19.605   513   513 W System.err:    at libcore.io.Linux.statvfs(Native Method)
10-13 09:36:19.605   513   513 W System.err:    at libcore.io.BlockGuardOs.statvfs(BlockGuardOs.java:330)
10-13 09:36:19.605   513   513 W System.err:    at android.system.Os.statvfs(Os.java:556)
10-13 09:36:19.605   513   513 W System.err:    at android.os.StatFs.doStat(StatFs.java:49)
10-13 09:36:19.605   513   513 W System.err:    ... 19 more
10-13 09:36:19.606   513   513 D AndroidRuntime: Shutting down VM
10-13 09:36:19.606   513   513 E AndroidRuntime: FATAL EXCEPTION: main
10-13 09:36:19.606   513   513 E AndroidRuntime: Process: com.seafile.seadroid2, PID: 513
10-13 09:36:19.606   513   513 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.seafile.seadroid2.SeadroidApplication: java.lang.IllegalArgumentException: Invalid path: /storage/41FE56CD5B7D9E05/Android/media
10-13 09:36:19.606   513   513 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at android.app.ActivityThread.-wrap1(Unknown Source:0)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
10-13 09:36:19.606   513   513 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Invalid path: /storage/41FE56CD5B7D9E05/Android/media
10-13 09:36:19.606   513   513 E AndroidRuntime:        at android.os.StatFs.doStat(StatFs.java:51)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at android.os.StatFs.<init>(StatFs.java:41)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at com.seafile.seadroid2.data.StorageManagerLollipop.getStorageSize(StorageManagerLollipop.java:31)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at com.seafile.seadroid2.data.StorageManager.fillLocationInfo(StorageManager.java:117)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at com.seafile.seadroid2.data.StorageManager.getStorageLocations(StorageManager.java:202)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at com.seafile.seadroid2.data.StorageManager.lookupStorageLocation(StorageManager.java:319)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at com.seafile.seadroid2.data.StorageManager.getStorageLocation(StorageManager.java:336)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at com.seafile.seadroid2.data.StorageManager.getThumbnailsDir(StorageManager.java:409)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at com.seafile.seadroid2.SeadroidApplication.initImageLoader(SeadroidApplication.java:44)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at com.seafile.seadroid2.SeadroidApplication.onCreate(SeadroidApplication.java:26)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
10-13 09:36:19.606   513   513 E AndroidRuntime:        ... 8 more
10-13 09:36:19.606   513   513 E AndroidRuntime: Caused by: android.system.ErrnoException: statvfs failed: EACCES (Permission denied)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at libcore.io.Linux.statvfs(Native Method)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at libcore.io.BlockGuardOs.statvfs(BlockGuardOs.java:330)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at android.system.Os.statvfs(Os.java:556)
10-13 09:36:19.606   513   513 E AndroidRuntime:        at android.os.StatFs.doStat(StatFs.java:49)
10-13 09:36:19.606   513   513 E AndroidRuntime:        ... 19 more
10-13 09:36:19.610   896  8289 W ActivityManager:   Force finishing activity com.seafile.seadroid2/.ui.activity.BrowserActivity
```

**Comment by eduardosm** [comment]
I think that `getStorageSize` at https://github.com/haiwen/seadroid/blob/master/app/src/main/java/com/seafile/seadroid2/data/StorageManagerLollipop.java#L30 should be wrapped with a try-catch like in `getStorageFreeSpace`.
