### ISSUE TITLE
Seadroid reupload pictures (from camera) to server after server deletion

### ISSUE THREAD

**Issue by ketoraire** [haiwen/seadroid#815]
Hello,

I Actually experience some trouble with my seafile community server.
My android phone re-upload every photos to the server even if I remove them from the seafile folder (via the app)

The only solution I have for the moment is to disable the photo upload from the app… but I need this feature…

I don’t understand why… the phone re upload over 600 photos… my other device don’t have any trouble
And no error on the server …

Server : CE 6.3.4
Android APP : 2.2.15

Any ideas ?

Thanks

**Comment by freeplant** [comment]
Have you turned off then turned on photo backup? When you re-enable photo backup, the local records for uploaded photos will be deleted and it will check the file list at the server and upload missing files.

**Comment by sosnicki** [comment]
Hi, I've the same problem. I tried to re-enable photo backup and it didn't help. It happend after the latest update from Google Play Store.

**Comment by sosnicki** [comment]
I've checked a few older versions from the github page. 

2.2.15 - reupload photos
2.2.14 - reupload photos
2.2.12 - reupload photos
2.2.11 - OK, photos deleted on the server aren't uploaded again.

**Comment by freeplant** [comment]
Re-upload photos is designed behaviour. It works like following:

Every time you re-turn on the photo backup feature, the App will check the file list at the sever side and the files at local and upload missing files.

**Comment by sosnicki** [comment]
I agree, that it's reasonable to re-upload all photos when I re-turn the photo backup feature, but it's happend even if I'm not touching backup settings. 

Consider the following scenario. I've enabled backup feature and take a photo. Seafile app has sent the photo to the server and I've deleted it from the server via Seafile desktop. During the next synchronization, my phone is still uploading the same photo to the server. 

Moreover, after the last Seafile app upgrade (2.2.14 from Google Play Store), which is installed on my second phone, the app has uploaded all photos and videos since april 2018. These photos were deleted from the server few moths ago but they are still on SD card.

**Comment by freeplant** [comment]
I don't have this problem in my phone. We will give the code a check.

**Comment by ketoraire** [comment]
Sosnicki has resume perfectly the situation.

On my side I try with 2.2.14:

- Disable backup
- Reboot
- Reenable backup 
- Remove picture from the server
- Verify transfert list on seadroid ... reuploaded again

With 2.2.15, i can't reenable the backup function

**Comment by de-es** [comment]
I can confirm the behavior described by @sosnicki since version 2.2.12. I just have to restart the app manually or with a reboot and reuploading starts again.

I tried every follow-up version with fresh installations, behavior stays the same. I switched back to 2.2.11 meanwhile because you have to delete items in source and target now which is kind of confusing.

**Comment by de-es** [comment]
As far as I experienced, this is solved with 2.2.18.

**Comment by ketoraire** [comment]
> As far as I experienced, this is solved with 2.2.18.

Still the same for me... :(

**Comment by sosnicki** [comment]
> > As far as I experienced, this is solved with 2.2.18.
> 
> Still the same for me... :(

I confirm that this issue is not solved. I update my seadroid from version 2.2.11 to 2.2.18 and it reuploads all deleted images and videos to the server. I checked that behavior on two smartphones.

Maybe it is possibile to add some logging to a text file which I could attach to this issue?

**Comment by de-es** [comment]
I am sorry, you are right. I was misleaded by a fresh installation, which - somehow - showed the behaviour first after several reboots.

**Comment by ketoraire** [comment]
Hello Guy,

Upgrade my server to 7.0.4 + app at 2.2.18 seem to solve the trouble for me.

**Comment by sosnicki** [comment]
> Upgrade my server to 7.0.4 + app at 2.2.18 seem to solve the trouble for me.

I've checked the fresh server installation (7.0.4), fresh application install (2.2.18) and it didn't work for me. Deleted photos are still reuploaded to the server.

@ketoraire, can you check if you have Video upload enabled?

I suppose that problem is in this part of code, but I didn't have time to check it:

```java
private void syncCamera() {
        SettingsManager settingsManager = SettingsManager.instance();
        CameraUploadManager cameraManager = new CameraUploadManager(getApplicationContext());
        if (cameraManager.isCameraUploadEnabled() && settingsManager.isVideosUploadAllowed()) {
            cameraManager.performFullSync();
        }
    }
```

**Comment by ketoraire** [comment]
Hi Sosnicki,

Photo Upload is enable on my app and work fine actually.

**Comment by sosnicki** [comment]
Hi Ketoraire,

I meant "Video upload" not just photos, because this checkbox cause reuploading in my opinion.

**Comment by ketoraire** [comment]
> Hi Ketoraire,
> 
> I meant "Video upload" not just photos, because this checkbox cause reuploading in my opinion.

You're right... still not working here :( My bad

**Comment by de-es** [comment]
@maxiaoping Any updates to this issue? I guess all participants are still 2.2.11 because of the apps behaviour.

**Comment by freeplant** [comment]
The problem is fixed in version 2.2.25.

**Comment by de-es** [comment]
Looks good so far. Thanks for fixing.

**Comment by ketoraire** [comment]
Seems good for me too
